name: D

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        dc:
          - dmd-latest
          - ldc-latest
          - dmd-beta
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ matrix.dc }}
    - name: 'Test'
      run: |
        dub test
        dub test :pcg
        dub test :rando
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dlang-community/setup-dlang@v1
      with:
        compiler: dmd-latest
    - name: 'Install dependencies'
      run: |
          sudo apt-get install libcurl4-openssl-dev
    - name: 'Test (with coverage)'
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        dub test -b unittest-cov
        dub test -b unittest-cov :pcg
        dub test -b unittest-cov :rando
        dub fetch doveralls
        dub run doveralls
